sonar.projectKey=andry12344321_GuessNumberProject2
sonar.organization=andry12344321
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/*.cshtml
sonar.test.inclusions=**/*Tests.cs
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml