name: GuessNumber CI/CD

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # для будущих версий Node.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Получаем код
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Устанавливаем .NET 8
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Восстановление зависимостей
      - name: Restore dependencies
        run: dotnet restore GuessNumber.sln

      # Сборка решения
      - name: Build solution
        run: dotnet build GuessNumber.sln --configuration Release

      # Запуск тестов
      - name: Run tests
        run: dotnet test GuessNumber.sln --logger "trx;LogFileName=test_results.trx"

  analysis:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Устанавливаем .NET 8
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Подсчёт строк через CLOC
      - name: Count lines of code with CLOC
        run: |
          choco install cloc -y
          cloc . > cloc-report.txt
          type cloc-report.txt

      # Запуск SonarCloud анализа
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
        run: |
          dotnet tool install --global dotnet-sonarscanner
          $env:PATH += ";$env:USERPROFILE\.dotnet\tools"
          dotnet sonarscanner begin /k:"andry12344321_GuessNumberProject2" /o:"$env:SONAR_ORG" /d:sonar.login="$env:SONAR_TOKEN"
          dotnet build GuessNumber.sln
          dotnet sonarscanner end /d:sonar.login="$env:SONAR_TOKEN"
